# Use root/example as user/password credentials
# version: '3.2'
#
# services:
#
#   database:
#     image: mysql:8.0.16
#     container_name: coins_db
#     ports:
#       - 3307:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: demo
#       MYSQL_USER: demo_user
#       MYSQL_PASSWORD: demo_pass
#     command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
